name: Deploy Policy Plan and Roles

env:
  REVIEWER: bcasey266 # Change this to a GitHub reviewer
  pacEnvironment: Bakery # Change this to a PAC environment name
  definitionsRootFolder: Definitions
  planFolder: Output

on:
  pull_request_review:
    types: [submitted]

jobs:

  deploy:
    name: Deploy Policy Plan and Roles
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      
    if: github.event.review.state == 'approved' && (contains(github.event.pull_request.labels.*.name, 'PolicyDeployment') || contains(github.event.pull_request.labels.*.name, 'RoleDeployment'))
    runs-on: ubuntu-latest

    environment: Bakery

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - shell: pwsh
        name: Install Required Modules
        run: |
          Install-Module Az.ResourceGraph -Force -Verbose -AllowClobber
          Install-Module Az.Resources -Force -Verbose -AllowClobber
          Install-Module EnterprisePolicyAsCode -Force
      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.ROLES_CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
      - name: Deploy Policy Plan
        if: contains(github.event.pull_request.labels.*.name, 'PolicyDeployment')
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Deploy-PolicyPlan -definitionsRootFolder $env:definitionsRootFolder -inputFolder $env:planFolder -pacEnvironment $env:pacEnvironment
          azPSVersion: "latest"
      - name: Deploy Role Plan
        if: contains(github.event.pull_request.labels.*.name, 'RoleDeployment')
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Deploy-RolesPlan -definitionsRootFolder $env:definitionsRootFolder -inputFolder $env:planFolder -pacEnvironment $env:pacEnvironment
          azPSVersion: "latest"
      - shell: pwsh
        if: contains(github.event.pull_request.labels.*.name, 'PolicyDeployment')
        name: Confirm PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if (Get-ChildItem $env:planFolder -recurse -include roles-plan.json) {
            gh pr edit $env:PR_NUMBER --add-label 'RoleDeployment' --remove-label 'PolicyDeployment'
            gh pr edit $env:PR_NUMBER --title 'Approval Required for Role Deployment' --remove-reviewer $env:REVIEWER
            gh pr edit $env:PR_NUMBER --add-reviewer $env:REVIEWER
          }
          else {
            gh pr close $env:PR_NUMBER --comment 'Changes deployed' --delete-branch
          }
      - shell: pwsh
        if: contains(github.event.pull_request.labels.*.name, 'RoleDeployment')
        name: Confirm PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr close $env:PR_NUMBER --comment 'Changes deployed' --delete-branch
          
